.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH ULTRAVIOLET 1 "MARCH 1995" Linux "User Manuals"
.SH NAME
Ultraviolet \- A fuse-sdl command line front-end with acces to
.B World of Spectrum
Online archive
.SH SYNOPSIS
.B python3 [pathTo]ultraviolet.py
.SH DESCRIPTION
.B Ultraviolet
provides access to the
.B World Of Spectrum
Online archive
.SH AUTHOR
Asier Alkorta <asier.alkorta@gmail.com>
.SH "SEE ALSO"
.BR fuse-sdl (1),

