#!/usr/bin/python3
__author__ = 'developer'
import ultraviolet.PlatformProviderSpectrum
import ultraviolet.MetadataProviderWorldOfSpectrumScraper
import ultraviolet.apputils


provider = ultraviolet.PlatformProviderSpectrum.PlatformProviderSpectrum()
metadataProvider = ultraviolet.MetadataProviderWorldOfSpectrumScraper.MetadataProviderWorldOfSpectrum()
metadataProvider.indexGames()