#!/usr/bin/python3
__author__ = 'developer'
import ultraviol.PlatformProviderSpectrum
import ultraviol.MetadataProviderWorldOfSpectrumScraper
import ultraviol.apputils


provider = ultraviol.PlatformProviderSpectrum.PlatformProviderSpectrum()
metadataProvider = ultraviol.MetadataProviderWorldOfSpectrumScraper.MetadataProviderWorldOfSpectrum()
metadataProvider.indexGames()