#!/usr/bin/python3
__author__ = 'developer'
import ultraviol.PlatformProviderSpectrum as pps
import ultraviol.spectrum.MetadataProviderWorldOfSpectrumScraper as mpWosS
import ultraviol.apputils


provider = pps.PlatformProviderSpectrum()
metadataProvider = mpWosS.MetadataProviderWorldOfSpectrum()
metadataProvider.indexGames()